modify_file_task:
  description: >
    Read the file located at {file_path} and make the following modifications: {modifications}.  
    Ensure the generated Python code is clean, follows best practices, and is free of errors.  
    The output should be a complete Python script that can be executed without issues.
    The Python script should have code for saving the file after modifications.The modifications should be combined with the original file content.
  expected_output: >
    A well-structured Python script that correctly implements the required modifications  
    to the file at {file_path}, ensuring efficiency and error handling.
    The Python script should have code for saving the file after modifications.The modifications should be combined with the original file content.
  agent: code_writer

execute_and_save_task:
  description: >
    Execute the provided Python code and apply the modifications directly to {file_path}.  
    Ensure that the modifications fully replace the necessary parts of the file while preserving integrity. 
  expected_output: >
    - The modifications successfully integrated into {file_path}. 
    - The updated file should be saved in the directory into this path {output_path} for future reference 
  agent: code_executor