modify_file_task:
  description: >
    Extract text and tables from the PDF at {file_path}, apply modifications: {modifications}, and generate a clean, documented Python script.
    The script should:
    - Extract content while preserving structure.
    - Modify tables and text as per the instructions.
    - Save the modified PDF while keeping the original integrity.
    - Include robust error handling and logging.
  expected_output: >
    A well-structured Python script that correctly implements the requested modifications using industry best practices.
  agent: code_writer

execute_and_save_task:
  description: >
    Execute the generated Python script to apply modifications to {file_path}, verify changes, and generate a PDF report.
    The process should:
    - Execute the script in a controlled environment to prevent security risks.
    - Log execution details, including modifications applied and errors encountered.
    - Verify the integrity of the modified PDF by comparing pre- and post-modification data.
    - Save a PDF report documenting the entire execution process.
  expected_output: >
    - Modified PDF with successful changes applied.
    - The updated file and the PDF report saved in the directory for future reference.  
    - Ensure the modified file is saved as {output_path} in a write-accessible directory.
  agent: code_executor
